"""add product source

Revision ID: 1bf1a093f580
Revises: 30d28388f362
Create Date: 2026-05-08 18:45:40.706430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bf1a093f580'
down_revision: Union[str, Sequence[str], None] = '30d28388f362'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column(
            "source",
            sa.String(length=50),
            server_default="manual",
            nullable=False,
        ),
    )    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'source')
    # ### end Alembic commands ###
