"""add receipt image path to products

Revision ID: 45a10b21fc58
Revises: 1bf1a093f580
Create Date: 2026-05-17 18:44:30.916959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45a10b21fc58'
down_revision: Union[str, Sequence[str], None] = '1bf1a093f580'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('receipt_image_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'receipt_image_path')
    # ### end Alembic commands ###
