"""add ai metadata to products

Revision ID: 60df4929cbb7
Revises: 45a10b21fc58
Create Date: 2026-05-18 17:56:47.250503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60df4929cbb7'
down_revision: Union[str, Sequence[str], None] = '45a10b21fc58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('ai_provider', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('ai_confidence', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'ai_confidence')
    op.drop_column('products', 'ai_provider')
    # ### end Alembic commands ###
