"""add warranty claim fields

Revision ID: b5a462f09674
Revises: bb91693dc983
Create Date: 2026-05-23 15:52:38.733886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5a462f09674'
down_revision: Union[str, Sequence[str], None] = 'bb91693dc983'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('warranty_provider', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('warranty_claim_url', sa.String(length=500), nullable=True))
    op.add_column('products', sa.Column('warranty_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'warranty_notes')
    op.drop_column('products', 'warranty_claim_url')
    op.drop_column('products', 'warranty_provider')
    # ### end Alembic commands ###
